<script src="{{ asset('/assets/plugins/datatables.net/js/jquery.dataTables.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('/assets/plugins/datatables.net-bs4/js/dataTables.bootstrap4.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('/assets/plugins/datatables.net-responsive/js/dataTables.responsive.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('/assets/plugins/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('/assets/plugins/datatables.net-autofill/js/dataTables.autoFill.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('/assets/plugins/datatables.net-autofill-bs4/js/autoFill.bootstrap4.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('/assets/plugins/datatables.net-colreorder/js/dataTables.colReorder.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('/assets/plugins/datatables.net-colreorder-bs4/js/colReorder.bootstrap4.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('/assets/plugins/datatables.net-keytable/js/dataTables.keyTable.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('/assets/plugins/datatables.net-keytable-bs4/js/keyTable.bootstrap4.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('/assets/plugins/datatables.net-rowreorder/js/dataTables.rowReorder.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('/assets/plugins/datatables.net-rowreorder-bs4/js/rowReorder.bootstrap4.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('/assets/plugins/datatables.net-select/js/dataTables.select.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('/assets/plugins/datatables.net-select-bs4/js/select.bootstrap4.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('/assets/plugins/datatables.net-buttons/js/dataTables.buttons.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('/assets/plugins/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('/assets/plugins/datatables.net-buttons/js/buttons.colVis.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('/assets/plugins/datatables.net-buttons/js/buttons.flash.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('/assets/plugins/datatables.net-buttons/js/buttons.html5.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('/assets/plugins/datatables.net-buttons/js/buttons.print.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('/assets/plugins/pdfmake/build/pdfmake.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('/assets/plugins/pdfmake/build/vfs_fonts.js') }}" type="text/javascript"></script>
<script src="{{ asset('/assets/plugins/jszip/dist/jszip.min.js') }}" type="text/javascript"></script>